"""create_initial_tables

Revision ID: af9b59348e46
Revises: 
Create Date: 2026-01-14 10:41:31.473296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af9b59348e46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_messages',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('parts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_id', sa.String(length=100), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_messages_user_group_id', 'model_messages', ['id', 'user_id', 'group_id'], unique=False)
    op.create_index('ix_model_messages_user_group_run_id', 'model_messages', ['id', 'user_id', 'group_id', 'run_id'], unique=False)
    op.create_table('model_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['model_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('provider_url', sa.String(length=500), nullable=True),
    sa.Column('provider_response_id', sa.String(length=200), nullable=True),
    sa.Column('provider_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('finish_reason', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['model_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_responses')
    op.drop_table('model_requests')
    op.drop_index('ix_model_messages_user_group_run_id', table_name='model_messages')
    op.drop_index('ix_model_messages_user_group_id', table_name='model_messages')
    op.drop_table('model_messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
